port: 80 # Port on which the load balancer will be running
healthCheckInSec: 20 # Health check every 20 seconds
strategy: "least-connections" # Load Balancer's load distribution Strategy, possible values -> "round-robin" | "weighted-round-robin" | "least-connections"
services: # Define your backend services, name and url is required. You should provide a weight for each service if using "weighted-round-robin" load distribution strategy
  - name: srv1
    url: http://localhost:9001
    weight: 30
  - name: srv2
    url: http://localhost:9002
    weight: 1
  - name: srv3
    url: http://localhost:9003
    weight: 1
