port: 9000
strategy: "least-connections"
services:
  - name: srv1
    url: http://localhost:9001
    weight: 30
  - name: srv2
    url: http://localhost:9002
    weight: 1
  - name: srv3
    url: http://localhost:9003
    weight: 1
