services:
  lb:
    build: .
    container_name: load-balancer
    ports:
      - "80:80"
    command:
      [
        "./lb",
        "--port",
        "80",
        "--services",
        "http://srv1:80,http://srv2:80,http://srv3:80",
        "--file",
        "config.yaml",
      ]
  srv1:
    image: strm/helloworld-http
  srv2:
    image: strm/helloworld-http
  srv3:
    image: strm/helloworld-http
