services:
  lb:
    build: .
    container_name: load-balancer
    ports:
      - "80:80"
    command: ["./lb", "-file", "config.yaml"]
  srv1:
    image: strm/helloworld-http
  srv2:
    image: strm/helloworld-http
  srv3:
    image: strm/helloworld-http
