services:
  lb:
    build: .
    container_name: load-balancer
    ports:
      - "9000:9000"
    command:
      ["./lb", "--services", "http://srv1:80,http://srv2:80,http://srv3:80"]
  srv1:
    image: strm/helloworld-http
  srv2:
    image: strm/helloworld-http
  srv3:
    image: strm/helloworld-http
